### PR TITLE
style update for https://nur.nix-community.org/

### PR DESCRIPTION
**Pull request by mipmip**
I did some work on the NUR website. Stuff of what I think should be generally be an improvement.

- nix community branding
  - favicon (the community logo)
  - seperated nur-themestyle
  - NUR logo
- at build the NUR readme.md gets downloaded and copied as documentation page
- header menu with relevant links
- footer menu with relevant links
- a few stats on the home page
- a credits page

Screenshot from 2021-11-22 17-52-40

### CODE REVIEW

**Comment by Mic92** [comment]
Cool. This already looks a lot better!

**Comment by Mic92** [comment]
Deployed manually because our CI for nur-search is still broken :(

**Comment by mipmip** [comment]
Thanks for the quick merge. I’ll have a look if I can help with the CI problems.

**Comment by Mic92** [comment]
ci is fixed again: https://github.com/nix-community/nur-search/commit/b52033c571a413c9826d5719cd376c935d54c50b

**Comment by Mic92** [comment]
I invited you to the NUR team.

**Comment by mipmip** [comment]
Thanks for the invitation. I accept :). I'm new in Nix-land but feel very much at home and I like to help.

**Pull request merged**
